root = "."
testdata_dir = "testdata"
tmp_dir = "../tmp"

[build]
args_bin = ["-configfile", "/${BH_CONFIG_FILE:-build.config.json}"]
bin = "../tmp/main"
cmd = "go build -gcflags='all=-N -l' -o ../tmp/main github.com/specterops/bloodhound/src/cmd/bhapi"
delay = 1
exclude_dir = []
exclude_file = []
exclude_regex = ["_test.go"]
exclude_unchanged = false
follow_symlink = false
full_bin = "dlv exec --accept-multiclient --log --headless --listen :2345 --api-version 2 ../tmp/main --"
include_dir = ["cmd/api/src", "packages/go"]
include_ext = ["go", "json"]
include_file = []
kill_delay = "0s"
log = "build-errors.log"
poll = false
poll_interval = 1
rerun = false
rerun_delay = 500
send_interrupt = false
stop_on_error = false

[color]
app = "blue"
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
main_only = false
time = false

[misc]
clean_on_exit = false

[screen]
clear_on_rebuild = false
keep_scroll = true
